import json
from datetime import datetime, time
from typing import List

from .session import PresenceSession
from .policy import Timetable, ScheduledPeriod, AttendancePolicyEngine

def run_demo():
    print("--- Phase 7A Replay Demonstration ---")
    
    # 1. Define Context
    period = ScheduledPeriod(
        period_id="per_123",
        subject_name="DBMS",
        room_id="201",
        start_time=datetime(2026, 9, 26, 10, 0),
        end_time=datetime(2026, 9, 26, 11, 0)
    )
    timetable = Timetable(periods=[period])
    
    print(f"\nTimetable Context:")
    print(f"Subject: {period.subject_name}")
    print(f"Room: {period.room_id}")
    print(f"Period: {period.start_time.strftime('%H:%M')}–{period.end_time.strftime('%H:%M')}")
    
    # 2. Define Input Sessions
    student_id = "11024010010"
    name = "Nimai Gupta"
    
    # Session: 10:02 to 10:45
    session1 = PresenceSession(
        session_id="sess_abc123",
        student_id=student_id,
        name=name,
        track_id="trk_1",
        entry_time=datetime(2026, 9, 26, 10, 2),
        last_seen_time=datetime(2026, 9, 26, 10, 45),
        exit_time=datetime(2026, 9, 26, 10, 45),
        duration_seconds=int((datetime(2026, 9, 26, 10, 45) - datetime(2026, 9, 26, 10, 2)).total_seconds()),
        status="CLOSED",
        camera_id="0",
        room_id="201"
    )
    
    sessions = [session1]
    
    print(f"\nPresence Sessions Generated by Tracking Engine:")
    for s in sessions:
        print(f"[{s.session_id}] {s.entry_time.strftime('%H:%M')} to {s.exit_time.strftime('%H:%M')} (Room: {s.room_id})")
        
    # 3. Policy Execution
    engine = AttendancePolicyEngine(
        present_threshold=0.75,
        partial_threshold=0.25,
        late_arrival_threshold_minutes=10
    )
    
    # Normally we aggregate sessions per student and find the period
    resolved_period = engine.resolve_period(sessions[0], timetable)
    if not resolved_period:
        print("\nCould not resolve a valid period for the sessions.")
        return
        
    record = engine.evaluate(student_id, name, resolved_period, sessions)
    
    print("\n--- Output Record ---")
    print(f"Student: {record.name}")
    print(f"Subject: {record.subject}")
    print(f"Period: {record.period_start.strftime('%H:%M')}–{record.period_end.strftime('%H:%M')}")
    print(f"Entry: {record.first_entry_time.strftime('%H:%M')}")
    print(f"Exit: {record.last_exit_time.strftime('%H:%M')}")
    
    minutes_present = record.qualifying_presence_seconds // 60
    print(f"Qualifying Presence: {minutes_present}m")
    
    print(f"\nStatus: {record.status}")
    print(f"Reason: {record.reason}")

if __name__ == "__main__":
    run_demo()
